### ISSUE TITLE
Space travelers' hub

### ISSUE THREAD

**Issue by iamsjunaid** [iamsjunaid/space-travelers-hub#49]
- Here is the link to [kanban-board](https://github.com/iamsjunaid/space-travelers-hub/projects/1).
- We're 3 coding partners working on this project.
    @iamsjunaid
    @AbdelazizSoliman 
    @wolterbwambale

**Comment by joel-kalema** [comment]
Hi Team

Your project is complete! 

# Congratulations! 🎉 

![ ](https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)
## Highlights

your Kanban board is well descriptive 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@joel-kalema** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
